export const categories = [
    {
      name: "Brands",
      items: [
        "Wet n wild",
        "Technic",
        "Maybelline",
        "Handaiyan",
        "Absolute New York",
        "Makeup Revolution",
        "Focallure",
        "Nyx",
        "Nior",
        "Ucanbe",
        "Rimmel",
        "Maange",
        "Cmaadu",
        "Everly",
        "Magefy",
        "Mac",
        "W7",
        "Beauty Glazed",
        "Imagic",
        "Milani",
        "L.A Girl",
        "J.Cat",
        "Sheglam",
        "Party Queen",
        "Phoera",
        "M.N",
        "Essence",
        "Pink Flash",
        "Victoria's Secret",
        "Pigment Play",
        "Lakme",
        "Bob",
        "Simple",
        "Pond's",
        "The Ordinary",
        "Tresemme",
        "Beauty Formula",
        "Ribana",
        "Cera Ve",
        "Cathy Doll",
        "Beauty of Joseon",
        "Some by Mi",
        "Lenbena",
        "Garnier",
        "Nivea",
        "Mama Earth",
        "Xpel",
        "The Derma Co",
        "The Body Shop",
        "Cosrx",
        "Missha",
        "3W Clinic",
        "Vaseline",
        "Freeman",
        "Melao",
        "Revolution",
        "Neutrogena",
        "Freyias",
        "Cetaphill",
        "Plum",
        "Breylee",
        "Matrix",
        "Bioderma",
        "Bioaqua",
      ],
    },
    {
      name: "Makeup",
      subCategory: [
        {
          name: "Face",
          items: [
            "Face Primer",
            "Concealer",
            "Foundation",
            "Pressed Powder",
            "Loose Powder",
            "Blush & Highlighters",
            "Bronzer & Contour",
            "BB & CC Cream",
            "Setting Spray",
            "Makeup Remover",
          ],
        },
        {
          name: "Eyes",
          items: [
            "Kajol",
            "Eyeliner",
            "Mascara",
            "Eyebrow",
            "EyeShadow",
            "Eyelash & Applicator",
          ],
        },
        {
          name: "Lips",
          itmes: [
            "Lipstick",
            "Lip Gloss",
            "Liquid Lipsticks",
            "Lipstick Set",
            "Lip Liner",
            "Lip Balm",
          ],
        },
        {
          name: "Nails",
          items: [
            "False Nails",
            "Nail Polish",
            "Nail Polish Remover",
            "Manicure & Pedicure Kits",
          ],
        },
        {
          name: "Brushes & Tools",
          items: [
            "Brushes",
            "Brush Cleanser",
            "Razor",
            "Eyebrow Razor",
            "Beauty Blender",
            "Powder Puff",
            "Mirrors",
            "Tweezers",
            "Sharpeners",
            "Eyelash Curler",
            "Makeup Pouches",
            "Makeup Cleansing Sponge",
          ],
        },
      ],
    },
    {
      name: "Skin Care",
      subCategory: [
        {
          name: "Face Care",
          items: [
            "Cream & Moisturiser",
            "Sunscreen",
            "Facewash & Cleanser",
            "Essence & Serum",
            "Eye Concern",
            "Toner",
            "Face Mask",
            "Face Pack",
            "Trial Kit",
            "Nose Stips",
            "Face Scrup & Exfoliators",
            "Facial Wipes",
          ],
        },
        {
          name: "Lip Care",
          items: ["Lip Balm", "Lip Oil", "Lip Mask", "Lip Scrub & Exfoliator"],
        },
        {
          name: "Body Care",
          items: [
            "Soap",
            "Bath Salt",
            "Body Lotion",
            "Sunscreen",
            "Body Spray",
            "Shower Gel",
            "Deodorants",
          ],
        },
        {
          name: "Hand & Foot",
          items: ["Hand Cream", "Foot Cream", "Mehendi"],
        },
        {
          name: "Shop By Concern",
          items: [
            "Acne Treatment",
            "Spot Treatment",
            "Oil Control Treatment",
            "Dry Skin Treatment",
            "Sunburn Treatment",
            "Pore Care",
            "Hair Treatment",
            "Anti-Aging Treatment",
          ],
        },
      ],
    },
    {
      name: "Hair Care",
      subCategory: [
        {
          name: "Hair Care",
          items: [
            "Shampoo",
            "Conditioner",
            "Hair Oil",
            "Hair Serum",
            "Hair Masks & Cream",
          ],
        },
        {
          name: "Hair Styling",
          items: ["Hair Color", "Hair Spray", "Gel & Waxes"],
        },
        {
          name: "Tools & Accessories",
          items: ["Hair Straightner", "Hair Brush", "Hair Comb", "Hair Dryers"],
        },
        {
          name: "Shop By Hair Type",
          items: ["straight", "Curley"],
        },
        {
          name: "Shop By Concern Hair",
          items: [
            "Hairfall & Thinning",
            "Dandruff",
            "Dry & Fizzy Hair",
            "Color Protection",
          ],
        },
      ],
    },
    {
      name: "Personal Care",
    },
    {
      name: "Shop",
    },
    {
      name: "Durga Puja Sale",
    },
    {
      name: "Clearance Sale",
    },
  ];